### ISSUE TITLE
LibreJS support

### ISSUE THREAD

**Issue by idk2848** [a1ix2/estrannaise.js#9]
Hello and thank you for making this project. I find it better than the simulator
available on transfemscience and I also appreciate how it is free software and 
includes the data it bases the numbers it uses on for calculations 

I would like to request that:

* the website serves readable, unobfuscated javascript
* that the website marks the license of files in a way that LibreJS can read

Many users concerned about their digital freedom make use of the LibreJS browser
extension and/or the GNU IceCat browser to avoid accidentally executing programs
which are proprietary through their browser (see The Javacript Trap[1]). As this
web based program is free software I think it should be marked as such so that it
is usable with the LibreJS extension by default 

I would have opened a PR for this myself as I thought it would be easy, however
I noticed that the webpage this project is hosted serves obfuscated javascript,
stripping whitespace, comments and meaningful variable names. Obfuscated
javascript cannot be considered Free any more than decompiled assembly code can

Documentation on Setting Your Javacript Free is available here[2]

Thank you in advance

[1] https://www.gnu.org/philosophy/javascript-trap.html
[2] https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by a1ix2** [comment]
Thanks for bringing this to my attention, we were experimenting with webpack, might revert to readable javascript in the future.

**Comment by a1ix2** [comment]
Next version is back to readable javascript.
